language: python

python: 
        - 3.0
        - 3.5

env:
        - DJANGO_VERSION=1.10

install: 
        - pip install -q Django==$DJANGO_VERSION
        - pip install -r requirements.txt

before_script:
        - python3 manage.py makemigrations
        - python3 manage.py migrate

script:
        - covarage run manage.py test
        - coveralls 
