package 'python-mock'
package 'ipython'
package 'gunicorn'
package 'flake8'
package 'pylint'
package 'python-django-extensions'

package 'python-pip'
execute 'pip install coveralls'
execute 'pip install django'
