# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default=b'', max_length=60)),
                ('data_de_nascimento', models.DateField(default=b'0000-00-00')),
                ('sexo', models.CharField(default=b'', max_length=10)),
                ('pre_fixo_telefone', models.CharField(default=b'', max_length=2)),
                ('telefone', models.CharField(default=b'', max_length=7)),
                ('celular', models.CharField(default=b'', max_length=8)),
                ('fax', models.CharField(default=b'', max_length=8)),
                ('cpf', models.CharField(default=b'', max_length=15)),
                ('rg', models.CharField(default=b'', max_length=13)),
                ('endereco', models.CharField(default=b'', max_length=60)),
                ('cidade', models.CharField(default=b'', max_length=20)),
                ('cep', models.CharField(default=b'', max_length=8)),
                ('estado', models.CharField(default=b'', max_length=20)),
                ('email', models.EmailField(default=b'', max_length=30)),
                ('grupo', models.CharField(default=b'', max_length=20)),
                ('titulo', models.CharField(default=b'', max_length=30)),
            ],
        ),
    ]
