# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default=b'', max_length=60)),
                ('data_de_nascimento', models.DateField(verbose_name=b'')),
                ('sexo', models.CharField(default=b'', max_length=10)),
                ('telefone', models.CharField(default=b'', max_length=7)),
                ('celular', models.CharField(default=b'', max_length=8)),
                ('fax', models.CharField(default=b'', max_length=8)),
                ('cpf', models.CharField(default=b'', max_length=15)),
                ('rg', models.CharField(default=b'', max_length=13)),
                ('endereco', models.CharField(default=b'', max_length=60)),
                ('cidade', models.CharField(default=b'', max_length=20)),
                ('cep', models.CharField(default=b'', max_length=8)),
                ('estado', models.CharField(default=b'', max_length=20)),
                ('email', models.EmailField(default=b'', max_length=30)),
                ('grupo', models.CharField(default=b'', max_length=20)),
                ('titulo', models.CharField(default=b'', max_length=30)),
                ('titulo_de_eleitor', models.CharField(default=b'', max_length=30)),
                ('zona', models.CharField(default=b'', max_length=30)),
                ('secao', models.CharField(default=b'', max_length=30)),
                ('profissao', models.CharField(default=b'', max_length=30)),
                ('cargo', models.CharField(default=b'', max_length=30)),
                ('empresa', models.CharField(default=b'', max_length=30)),
                ('dependente_nome', models.CharField(default=b'', max_length=30)),
                ('dependente_aniversario', models.CharField(default=b'', max_length=30)),
                ('dependente_parentesco', models.CharField(default=b'', max_length=30)),
                ('dependente_partido', models.CharField(default=b'', max_length=30)),
                ('dependente_data_filiacao', models.DateField(verbose_name=b'')),
            ],
        ),
    ]
